### ISSUE TITLE
4.0.0 release broken - wheel is missing modules

### ISSUE THREAD

**Issue by peterfarrell** [theatlantic/django-xml#18]
The `4.0.0` wheel release of the package only has the `__init__.py` file and is missing all the modules. It likely should be yanked from PyPI.

![Image](https://github.com/user-attachments/assets/ad70215d-faad-436a-a5c8-3394710e807d)

Screenshot of wheel contents from: https://files.pythonhosted.org/packages/1e/84/c61dd94e23568aae73ee3ec12ea75fbf4e00b02509a9250b6227aaaa7712/django_xml-4.0.0-py3-none-any.whl 

Also, there is no `v4.0.0` tag in GitHub (appears that `main` is the current `4.0.0` release code).

One potential fix is to add the missing modules to the list of packages (or use a custom `find()`).

```toml
[tool.setuptools]
zip-safe = false
platforms = ["any"]
packages = ["djxml", "djxml.xmlmodels", "djxml.xmlmodels.fields"]
include-package-data = false
```
